---
title: "Subsetting and annotation of Adipocytes"
author: "Johanne D. Madsen"
date: '`r Sys.Date()`'
format:
  html:
    embed-resources: true
execute: 
  echo: false
  warning: false
---

```{r setup}

library(dplyr)
library(Seurat)
library(patchwork)
library(qs)
library(harmony)
library(ggplot2)
Adipocytes_common<-qread("/work/without_ambientRNAremoval/data/Adipocytes_common_clean.qs")

```

```{r}

Adipocytes_donor_list <- Adipocytes_common %>%
  SplitObject(split.by = "Donor")


# 2. LogNormalize RNA data
Adipocytes_donor_list <- lapply(Adipocytes_donor_list, function(seurat_obj){
  output <- Seurat::NormalizeData(seurat_obj,
                                  assay = "RNA",
                                  verbose = TRUE)
  return(output)
})



Adipocytes_common <- purrr::reduce(Adipocytes_donor_list, merge)
DefaultAssay(Adipocytes_common) <- "RNA"

Adipocytes_common<-Seurat::FindVariableFeatures(Adipocytes_common,
                                  assay = "RNA",
                                  verbose = TRUE)

 
Adipocytes_common <- ScaleData(Adipocytes_common, split.by="Donor")



Adipocytes_common <- Adipocytes_common %>%
  RunPCA(seed.use = 1000,
         verbose = TRUE)
```


```{r}
Adipocytes_common <- Adipocytes_common %>%
  harmony::RunHarmony(
    group.by.vars = "Pool",
    assay.use = 'RNA',
    reduction.save = 'harmony.pca.RNA',
    project.dim = F,
    kmeans_init_nstart=20,
    kmeans_init_iter_max=100
  )

# UMAP
Adipocytes_common <- Adipocytes_common %>%
  Seurat::RunUMAP(
    dims = 1:20,
    reduction = 'harmony.pca.RNA',
    reduction.name = 'umap.rna',
    reduction.key = 'rnaUMAP_',
    seed.use = 1000,
    verbose = TRUE)

```

```{r}
Adipocytes_common <- Adipocytes_common %>%
  Seurat::FindNeighbors(reduction = "harmony.pca.RNA",
                        dims = 1:20, compute.SNN = TRUE)%>% 
  Seurat::FindNeighbors(reduction = "harmony.pca.RNA",
                        dims = 1:20, return.neighbor = TRUE)
#Do twice. Once with compute.SNN = TRUE, once with return.neighbor = TRUE. Can't run both


# Run UMAP dimensional reduction based on WNN
Adipocytes_common <- Adipocytes_common %>%
  RunUMAP(
    nn.name = "RNA.nn",
    reduction.name = "umap.snn",
    reduction.key = "snnUMAP_",
    seed.use = 1000)

# Cluster determination
Adipocytes_common <- Adipocytes_common %>%
  FindClusters(
    graph.name = "RNA_snn",
    algorithm = 3,
    res =0.1,
    random.seed = 1000,
    verbose = TRUE
  )

Adipocytes_common <- Adipocytes_common %>%
  FindClusters(
    graph.name = "RNA_snn",
    algorithm = 3,
    res =0.1,
    random.seed = 1000,
    verbose = TRUE
  )

```


```{r}

snn_dim <- DimPlot(Adipocytes_common,
                   reduction = 'umap.snn',
                   label.size = 3,
                   label = TRUE)

snn_harmony <- DimPlot(Adipocytes_common,
                       reduction = 'umap.snn',
                       group.by = "Pool",
                       label.size = 3)
snn_saf <- DimPlot(Adipocytes_common,
                       reduction = 'umap.snn',
                       group.by = "saf",
                       label.size = 3)
snn_donor <- DimPlot(Adipocytes_common,
                       reduction = 'umap.snn',
                       group.by = "Donor",
                       label.size = 3, split.by = "saf")
snn_splitsaf<-DimPlot(Adipocytes_common, reduction = 'umap.snn',
                       label.size = 3, split.by = "saf")
snn_dim 
snn_harmony
snn_saf
snn_donor
snn_splitsaf
```


```{r}

Adipocyte.markers <- FindAllMarkers(Adipocytes_common, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)
Adipocyte.markers %>%
    group_by(cluster) %>%
    slice_max(n = 2, order_by = avg_log2FC)

Adipocyte.markers %>%
    group_by(cluster) %>%
    top_n(n = 10, wt = avg_log2FC) -> top10


Adipocytes_heatmap<-DoHeatmap(Adipocytes_common, features = top10$gene) + NoLegend()

Adipocytes_heatmap
```

After seeing how weak the marker genes were we decided keep them as one cluster
```{r}
new_names <- c("Adipocytes","Adipocytes")
names(new_names) <- levels(Adipocytes_common)


Adipocytes_common <- RenameIdents(object =Adipocytes_common, new_names)
snn_ann<-DimPlot(Adipocytes_common,reduction = 'umap.snn', label = F) + NoLegend()
snn_ann

```





```{r}
Adipocytes_common$Label <- 1
Adipocytes_common@meta.data[ Adipocytes_common@meta.data$seurat_clusters == "0","Label"] <- 1 

Adipocytes_common@meta.data$Label <- factor(x = Adipocytes_common$Label, levels = c("1"))
Adipocytes_common <- SetIdent(Adipocytes_common, value = Adipocytes_common$Label) #Sets the identity class value for cells


## Fix cluster labels
Adipocytes_common$Annotation <- "NA"
Adipocytes_common@meta.data[ Adipocytes_common@meta.data$Label %in% 1,"Annotation"] <- "Adipocytes" 


Adipocytes_common@meta.data$Label <- factor(x = Adipocytes_common$Label, levels = c("Adipocytes"))

Adipocytes_common <- SetIdent(Adipocytes_common, value = Adipocytes_common$Annotation) #Sets the identity class value for cells



```

```{r}
#qsave(Adipocytes_common,"/work/without_ambientRNAremoval/data/Adipocytes_common_Annotated.qs")


```
